### ISSUE TITLE
Snap to Waveform

### ISSUE THREAD

**Issue by BillMills** [GRIFFINCollaboration/SpectrumViewer#10]
Snap to waveform dropped until I have some waveforms to test on.

**Comment by AdamGarnsworthy** [comment]
GRIFFIN will be reading iut waveforms this evening and overnight so you can test the waveform snap functionality.

**Comment by katieannemills** [comment]
ok, reimplemented - only thing is, the old code used to snap to 256 bins in x, while the current waveforms seem to be 4006 (?) bins long; snapping to the full size, let me know if there was actually a reason for 256.

**Comment by AdamGarnsworthy** [comment]
256 was probably some kind of test did. Use the slectrum length as it will change regularly.

**Comment by katieannemills** [comment]
done.
