### ISSUE TITLE
Async fitting (was: Gain matcher ready to ship)

### ISSUE THREAD

**Issue by BillMills** [GRIFFINCollaboration/SpectrumViewer#12]
Hi folks - GRIFFIN's new gain matching tool is almost ready to ship :ship:; have a look at the [demo here](http://griffincollaboration.github.io/SpectrumViewer/gainMatcher.html). A few comments:

 - Conspicuously absent is a button to write results to the ODB; this will be implemented once we're happy with the behavior of the rest of the app.
 - Wait 5ish seconds on page load; an initial attempt at gain matching proceeds automatically, but it takes a few seconds to do 128 fits.
 - If GRIFFIN isn't currently pointed at a 60-Co or 152-Eu source, the results will look silly; to see things do something a bit more sensible regardless of what spectrum is currently being broadcast by the analyzer, try changing the energies of the peaks in the input boxes at the top, to point the fitting at peaks that are actually present. Initial region-of-interests are guesstimated as 30 bins up and down from the bin equal to the peak energy in keV - so if you have a peak at 900 keV, the algorithm will look around for it in *bins* 870 to 930.

cc comments @AdamGarnsworthy @SmithJK

**Comment by SmithJK** [comment]
Found this error yesterday morning.
![gain_match_error](https://cloud.githubusercontent.com/assets/10604745/10822440/7f40d29e-7e14-11e5-9e59-2e3c1e7c2674.png)

**Comment by katieannemills** [comment]
Yep, that sometimes happens when the fits are proceeding; not an error, browsers just don't expect long blocking calculations. Just wait for the script to finish (on my laptop, all fits proceed in ~5s).

**Comment by katieannemills** [comment]
Although, it might be possible to suppress this with a web worker - I'll look into it, but it won't actually change execution time - 128 fits are always going to take a few seconds.

**Comment by katieannemills** [comment]
Update: spent the day experimenting with web workers - we can indeed push fitting off to another thread, but spawning 128 background threads is many times slower than just waiting a few seconds. Progress is in the `async-fits` branch; best solution is likely to spawn a single background thread that does all the fits as a batch, and then have a separate fitting path for re-doing individual fits.

May revisit in future, but for now I'm filling this under "ain't broke, don't fix it" :) Fun learning task (for me) though - thanks for pointing it out!

**Comment by katieannemills** [comment]
Aha! Turns out you can make a serial-but-non-blocking fake for loop using `setTimeout`, which will prevent the crabby browser complaints @SmithJK pointed out, and allows us to have a super neato progress bar, too. For those interested in the funkiest implementation of a for loop ever, see `scripts/helpers.js releaser()`.

Closing out - web workers were fun and all, but no need to overkill this problem.
