### ISSUE TITLE
Spectrum menu

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/SpectrumViewer#13]
Please change order of drop-down menus:
Hitpatterns
Sum Spectra
GRIFFIN energy, time, pulse height, waveform
Sceptar energy, time, pulse height, waveform
DESCANT energy, time, pulse height, waveform, ZC, LI, SI

**Comment by katieannemills** [comment]
sorry - this looks like the order they are already in; how do they show up for you?

**Comment by AdamGarnsworthy** [comment]
![screen shot 2015-10-27 at 11 21 20 pm](https://cloud.githubusercontent.com/assets/5225574/10781096/86f2bea8-7d01-11e5-9b8b-27a660d5b0f5.png)

**Comment by AdamGarnsworthy** [comment]
Weird

**Comment by AdamGarnsworthy** [comment]
I see the same on my chrome on android

**Comment by katieannemills** [comment]
whoa yep, I see the same thing in chrome.

Looks good in firefox - I'll look into it.

**Comment by katieannemills** [comment]
fixed - turns out Chrome is super inflexible about its sort algorithms.
