### ISSUE TITLE
Y axis tick mark

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/SpectrumViewer#14]
Fix axis tick mark selections - a plot with a range of between 90 and 110 with 4-5 ticks should tick at 20, 40 and 80 not 21, 43 etc. Use sensible value selections.

**Comment by katieannemills** [comment]
fixed in feature branch - ticks restricted to powers of 10 or (powers of 10)/2. Will appear in production with the rest of this week's features after tidy-up.
