### ISSUE TITLE
More compact control panel 

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/SpectrumViewer#15]
More compact control panel - x-axis control is good size, but stuff below that is too large/spread out.  Add prev/next view buttons.  Add bin content to x,y position.

**Comment by katieannemills** [comment]
- ~~More compact control panel - x-axis control is good size, but stuff below that is too large/spread out.~~ <-- done as part of layout refactor
- ~~Add prev/next view buttons.~~
- Add bin content to x,y position.

These last two are good ideas - need to polish existing features and tidy up before we tack on any more features, but can probably do this on the flight to brooklyn next weekend.

**Comment by katieannemills** [comment]
Come to think of it - which bin content do you mean? If there's a bunch of spectra plotted, it might get confusing to list out each of their contents.
