### ISSUE TITLE
minimizable panels

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/SpectrumViewer#18]
Spectrum list and plot control minimisable.
So plot can take most of page - make so can either scroll or resize to fill page with no scrollbars.

**Comment by katieannemills** [comment]
Today's work addresses this issue, along with #15 #16 #17.

By moving the plot selection to a horizontal row of dropdowns, we achieve several things:
- we can combine them with the header, to minimize the combined space used (re: #17)
- we can scroll away from them, allowing us to dismiss them without any unreliable layout kludges (this issue)
- we can use the right sidebar space for the plot control UI, tidying it up (#15), but also making it available without scrolling while looking at the plot; same goes for the cursor reporting (#16).

~~Yes, this breaks the heck out of the other two spectrum viewer apps - no, those problems won't be hard to fix.~~ <-- fixed.

**Comment by katieannemills** [comment]
done as part of the larger layout refactor spanning the issues mentioned above.
