### ISSUE TITLE
Multiple canvases

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/SpectrumViewer#19]
would like to allow several spectrum panels - axis controls will need selector to current/all/selected canvas. Plot control will need add/overlap selection

**Comment by katieannemills** [comment]
implemented on `x-tag-template` branch, ready to ship pending code cleanup & documentation - early next week.

This represents a large refactor of this project to use some bare-bones custom elements combined with client-side templating, serving as a proof of principle that we can refactor the dashboard to be client-side-only (at least in terms of custom elements + templates).
