### ISSUE TITLE
Gain matcher ODB writing

### ISSUE THREAD

**Issue by katieannemills** [GRIFFINCollaboration/SpectrumViewer#22]
Do we have a preferred plan for security re: writing gain match coefficients to the odb? I need to look into the security options there still, but as I recall doing authenticated ajax requests was problematic. Don't want to expose a 'write to odb' button until we have a good plan for dealing with this.

**Comment by AdamGarnsworthy** [comment]
If the fitter obtains NaN for the slope it should write "1" to odb. If the fitter obtains NaN for the offset it should write "0" to odb.
