### ISSUE TITLE
GainMatcher

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/SpectrumViewer#26]
The order of the slope and offset columns in the main table should be reversed. (slope 1st).

**Comment by AdamGarnsworthy** [comment]
There is a problem with the process here (I think).

The analyzer takes the coefficients from the ODB and applies them to the pulse-height to get the energy spectrum. Presently the gain-matcher is taking these energy spectra and fitting them to determine the gain-matching coefficients and then writing them to the odb. These will not work as they are then a combination of the original coefficients and the new ones.
A better approach is to take the pusle-height spectrum and use it to determine the coefficients. Then write these to the odb.

In the analyzer code:
//Pulse-Height spectrum:
spec_store_Pdata[web_chan][ptr->energy[i]/ptr->kvalue[i]]++;

//Energy spectrum:
ECal = (int)(spread( ((float)ptr->energy[i])/ptr->kvalue[i] ) \* gains[i] + offsets[i]);        spec_store_Edata[web_chan][ECal]++;

**Comment by AdamGarnsworthy** [comment]
There should be a button next to "Automate gain match" to grab a fresh set of spectra from the analyzer (ie repeat the process of download that happens when the page loads).

**Comment by katieannemills** [comment]
- columns: fixed
- pulse height: fixed
- fresh spectra: why not just refresh?

**Comment by AdamGarnsworthy** [comment]
ok will just refresh.
Works smoothly.
-Need to add a check-box for each line. If I only want to load say 4 entries to the ODB I cant right now, I have to load all or nothing. Include "check all" and "uncheck all" buttons as well. Default is checked if the fitter is happy.
