### ISSUE TITLE
some very early progress

### ISSUE THREAD

**Issue by BillMills** [GRIFFINCollaboration/SpectrumViewer#5]
@AdamGarnsworthy, work has begun on modernizing and integrating the various spectrum viewer projects; a [demo is in progress here](http://griffincollaboration.github.io/SpectrumViewer/).

As it stands, I've replaced x-tags with bootstrap (for more reliable cross-browser performance), and reused the Ultralight framework we developed for the CSB to make URL parameters and HTML templating a simple matter; the demo linked above also includes the collapsible menus you requested. I expect to be at feature parity with the original version in very short order, whereupon we can dig into the forks and branches early next week; feel free to visit the link above to observe progress as it evolves.

**Comment by AdamGarnsworthy** [comment]
Looks good and sounds like excellent progress. Default behaviour for the menus should be collapsed on load. In this demo you should include more than 9 spectra so we can test the exceptions which are applied for trying to grab >10 at one time.
