### ISSUE TITLE
server CORS support

### ISSUE THREAD

**Issue by BillMills** [GRIFFINCollaboration/SpectrumViewer#9]
Hi @AdamGarnsworthy,

I'd like to fiddle with the spectrum server a bit:

 - Add cross origin support so we don't have to load this via script tags (use batch promises instead, better for pulling in information from multiple sources, which is something we might like to do someday).
 - remove JSONP wrappers (don't need them if we use CORS+promises instead).

Two questions:
 - Does anyone besides the spectrum viewer rely on the JSONP wrapping?
 - Are there deploy instructions for this? I see what looks like the server code sitting in `/home/griffin/daq/analyser/web_server.c` with compile instructions at the top, but there's no obvious executable nearby; once this is compiled, what is the preferred method for getting it going?

**Comment by AdamGarnsworthy** [comment]
I don't think anything else depends on thus server format apart from the various versions of the spectrum viewer for the rate monitoring and gain-matching.

Please don't break the online analyzer during development, we use this constantly. Eslecially in preparing for the beamtime next week.

Code compiles under the Makefile in that folder. Executable is the analyzer which is lauched using the wiki instructions under Midas clients for griffin.

**Comment by AdamGarnsworthy** [comment]
The instructions are in your readme from the first version of the spectrum viewer. We developed the server and client simultaneously

**Comment by BillMills** [comment]
Ah, I see instructions on the web server's current API in the README, but what I was looking for is in the wiki - thanks! As for breaking the analyzer, I seriously doubt it; I'm going to add one line to the web server's response header, and take the JSONP wrappers off - I'd be shocked if that affects the rest of the analyzer.

**Comment by BillMills** [comment]
Alright, start a run and check it out: http://griffincollaboration.github.io/SpectrumViewer/

Notice that this has nothing to do with service from MIDAS - we can serve this anywhere we like.

**Comment by AdamGarnsworthy** [comment]
This one seems to work: http://griffincollaboration.github.io/SpectrumViewer/
but as I tried to warn you, this one: http://grsmid00.triumf.ca:8081/CS/SpectrumViewer
, the main one that we use for the experiment, is now not working because the server changed.

**Comment by AdamGarnsworthy** [comment]
-Opening one drop-down menu should auto-close all the others.
-How do I clear all spectra now? Before we had the list at the bottom but now I have to scroll through and find which ones I displayed to remove them. Is there a fats way to do this?
-Peak fitting does not work for me (Google Chrome on MAC: V 45.0.2454.93), will only put the first marker and then no further response.

**Comment by BillMills** [comment]
Don't worry - the new one will be fully operational this weekend.

 - Fitting: fixed.
 - Clear all: dropped that - will re-implement Friday.
 - one drop down at a time: also easily done on Friday.

**Comment by BillMills** [comment]
Do you want to be able to use SpectrumViewer2 immediately? Retrofitting this to talk to the new server can be done quickly without waiting for a full rebuild. Let me know if this matters and that can get done Friday too.

**Comment by AdamGarnsworthy** [comment]
SpectrumViewer1 is the main priority. The auto-gainmatching stuff can wait until Monday.

**Comment by AdamGarnsworthy** [comment]
-x,y cursor values displayed on mouse-over have disappeared.

**Comment by AdamGarnsworthy** [comment]
-snap to waveform feature missing (waveforms are not being read out in the data at the moment so this is difficult to test).

**Comment by AdamGarnsworthy** [comment]
-entering x min>max and x max<min values is not handled elegantly in all cases. Gets into a funny state.

**Comment by BillMills** [comment]
- all yesterday's comments have been fixed & pushed
 - x-y: dropped it on purpose, but sure, it can come back
 - waveform: also dropped on purpose, but it can come back when there's a waveform to test on.
 - min / max: sure, we can watch for that.

**Comment by BillMills** [comment]
alright - these are all live except the waveform snap; I'll open a separate issue for that.
